FROM resin/%%RESIN_MACHINE_NAME%%-alpine:latest

# install cron, rsnapshot, openssh-client
RUN apk add --no-cache \
	curl \
	dcron \
	rsnapshot \
	openssh-client

# install filesystem overlay
COPY . ./

# set timezone
RUN apk add --no-cache tzdata
ENV TZ=America/Toronto

# create snapshots mount point
RUN mkdir /snapshots

CMD ["/bin/bash", "start.sh"]
