#!/usr/bin/with-contenv bash
# shellcheck shell=bash

s6-echo "Stopping plymouth service"
# prevent plymouth from blocking fbcp
# https://github.com/klutchell/balena-pihole/issues/25
# https://github.com/balena-os/meta-balena/issues/1772
dbus-send \
    --system \
    --dest=org.freedesktop.systemd1 \
    --type=method_call \
    --print-reply \
    /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit \
    string:"plymouth-quit.service" string:"replace"

s6-echo "Starting PADD"

# fix for PADD fonts
sed -i "s/^FONTFACE.*/FONTFACE=\"${FONTFACE}\"/" /etc/default/console-setup
sed -i "s/^FONTSIZE.*/FONTSIZE=\"${FONTSIZE}\"/" /etc/default/console-setup
dpkg-reconfigure console-setup 2> /dev/null > /dev/tty1

# wait for pihole api to become available
sleep 20

/usr/src/app/padd.sh 2> /dev/null > /dev/tty1
