
ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/a173c8a2e730f2a75f24fe75c592e631:1.92.5 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/c1f408899e1788d0d4179bc608a0d4be:1.92.5 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/12b766c1ac7098fc03050d0433a10377:1.92.5 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

ENV TS_HOSTNAME="pi-hole"
ENV TS_EXTRA_ARGS="--accept-dns=false --reset"
