
ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/ab32cea7314a032e323e336a73303bd0:1.96.4 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/80b192d9c067ad4342efb851219e74a1:1.96.4 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/bd1dc730104aa2c02e350137a5495d19:1.96.4 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

ENV TS_HOSTNAME="pi-hole"
ENV TS_EXTRA_ARGS="--accept-dns=false --reset"
