#!/command/with-contenv bash
# shellcheck shell=bash

# quit the plymouth (balena logo) service so that we can see the TTY
s6-echo "Stopping plymouth service..."
dbus-send \
    --system \
    --dest=org.freedesktop.systemd1 \
    --type=method_call \
    --print-reply \
    /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit \
    string:"plymouth-quit.service" string:"replace"

s6-echo "Setting console font to ${FONTFACE} ${FONTSIZE}..."
sed -i "s/^FONTFACE.*/FONTFACE=\"${FONTFACE}\"/" /etc/default/console-setup
sed -i "s/^FONTSIZE.*/FONTSIZE=\"${FONTSIZE}\"/" /etc/default/console-setup
dpkg-reconfigure console-setup 2> /dev/null > /dev/tty1

# see https://github.com/klutchell/balena-pihole/issues/187
s6-echo "Detecting screen size..."
console_height="$(stty size -F /dev/tty1 | awk '{print $1}')"
console_width="$(stty size -F /dev/tty1 | awk '{print $2}')"

sed "s|console_height=.*|console_height=$console_height|" -i /usr/local/bin/padd
sed "s|console_width=.*|console_width=$console_width|" -i /usr/local/bin/padd

s6-echo "Starting PADD..."
/usr/local/bin/padd 2> /dev/null > /dev/tty1
