name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [gh_klutchell/pi-hole, klutchell_apps/pi-hole]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: balena-io/deploy-to-balena-action@61a347b1b9fa00afbc8e117f0f280e989d02d7cb # v2.3.0
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
