name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [gh_klutchell/pi-hole, klutchell_apps/pi-hole]

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: balena-io/deploy-to-balena-action@31d0b891b057ae02329ab9874ccd0f1239e3c792 # v2.0.72
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          create_tag: true
